### ISSUE TITLE
Allow for https/ssl setup with puppetlabs apache

### ISSUE THREAD

**Issue by wadells** [ScottWales/puppet-reviewboard#15]
Currently the puppetlabs/apache provider forces port 80:

https://github.com/ScottWales/puppet-reviewboard/blob/v1.0.1/manifests/provider/web/puppetlabsapache.pp#L68

This prevents this provider from being used with https.

**Comment by ScottWales** [comment]
It may be helpful to have a way to provide custom config hash to apache, e.g.

```
reviewboard::provider::web {$site:
    config => { port => 443, ssl => true }
}
```

**Comment by wadells** [comment]
I've got https working in a custom provider I wrote that mirrors much of what is in the builtin puppetlabsapache.pp.  I'll see if I can find some time this week to abstract the configuration and upstream it, as it is rather hardcoded to my specific deployment at the moment.

We'll have to be careful here, or else we may end up plumbing the vast majority of apache::vhost configuration options through the provider.  I don't know how you feel about that, but to me it feels close to reinventing the apache configuration interface, with our own custom tweaks and api differences.

**Comment by ScottWales** [comment]
You should be able to pipe options directly to apache & leave the logic to the apache class, e.g.

```
define reviewboard::provider::web::puppetlabsapache (
    $vhost,
    $config = {},
) {
    $apache_defaults = {
        port => 80,
    }

    $vhost_config = merge($apache_defaults, $config)

    create_resources('apache::vhost', {"${vhost}" => $vhost_config})
}
```
