### ISSUE TITLE
enhancement: allow package to be installed through yum

### ISSUE THREAD

**Issue by wadells** [ScottWales/puppet-reviewboard#17]
To break the currently somewhat hard dependencies on pip (issue #11) and 'python-devel' (issue #16) we may consider having a provider argument to `reviewboard::package`.

Specifically, since effort has already been put into yum/rpm packaging for Review Board, I'd like to be able to use the yum package manager.

https://admin.fedoraproject.org/updates/search/ReviewBoard

I'm thinking a good initial scope for `reviewboard::package::provider` class param would be 'yum' and 'pip' as those are both providers recognized by the standard package resource:

http://docs.puppetlabs.com/references/latest/type.html#package-attribute-provider

The current `reviewboard::package` effectively uses a pip provider, though somewhat handrolled with a hybrid of easy_install and pip.  We could clean this up, and keep the default for the provider param as 'pip' to keep the default behavior consistent.

**Comment by ScottWales** [comment]
Makes sense - the reason I set up the install using easy_install was because I'm using a custom reviewboard plugin, which needs the interface available in the 2.0 beta. Probably a good idea to use yum for released versions

**Comment by wadells** [comment]
I think the builtin package resource with `provider => pip` can meet the needs of your cutting edge use case if we also leverage the `source => '<url>'` param.  I'll poke around and see if I can put together a patch tonight
